#!/usr/bin/env node
/**
 * docs/design/RESPONSIVE_REPORT.md — the responsive evidence, written out.
 *
 * Every line is read from review/responsive.json, which is produced by the
 * harness in the same run. Nothing here judges; the harness judged, and this
 * renders what it found with a link to the screenshot that shows it.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "../../..");
const DATA = join(REPO, "review/responsive.json");
const OUT = join(REPO, "docs/design");

if (!existsSync(DATA)) {
  console.error("review/responsive.json is missing — run the responsive harness first");
  process.exit(1);
}
const r = JSON.parse(readFileSync(DATA, "utf8"));
mkdirSync(OUT, { recursive: true });

const MARK = { pass: "✓ Pass", minor: "⚠ Minor issue", fail: "✗ Fail" };

/** Issues collapse across widths: the same defect at four widths is one defect
 *  with a range, not four findings. */
const collapse = (issues) => {
  const by = new Map();
  for (const i of issues) {
    const key = `${i.kind}|${i.says.replace(/^\d+pt: /, "")}`;
    if (!by.has(key)) by.set(key, { kind: i.kind, severity: i.severity, says: i.says.replace(/^\d+pt: /, ""), widths: [] });
    by.get(key).widths.push(i.width);
  }
  return [...by.values()].sort((a, b) => (a.severity === b.severity ? 0 : a.severity === "fail" ? -1 : 1));
};

const rows = r.screens.map((s) => {
  const c = collapse(s.issues);
  const kinds = [...new Set(c.map((i) => i.kind))];
  return `| ${s.name} | ${MARK[s.verdict]} | ${kinds.length ? kinds.join(", ") : "—"} |`;
}).join("\n");

const detail = r.screens.filter((s) => s.verdict !== "pass").map((s) => {
  const c = collapse(s.issues);
  return `### ${s.name} — ${MARK[s.verdict]}

${c.map((i) => `- **${i.kind}** (${i.widths.join(", ")}pt) — ${i.says}`).join("\n")}

Screenshots: ${r.widths.map((w) => `[${w}pt](../../review/responsive/${s.name}@${w}.png)`).join(" · ")}
`;
}).join("\n");

const heightTable = r.screens.map((s) =>
  `| ${s.name} | ${r.widths.map((w) => `${s.heights[w]}px`).join(" | ")} |`).join("\n");

const md = `# Responsive Report

Generated by \`tools/review/responsive.mjs\`. Do not edit by hand — every value
below is measured from a live document in the run that produced this file.

**Widths:** ${r.widths.map((w) => `${w}pt`).join(" · ")} — reference ${r.reference}pt.
**Result:** ${r.pass} pass · ${r.minor} minor · ${r.fail} fail, across ${r.screens.length} screen states
(${r.screens.length * r.widths.length} renders).

No layout was changed to produce this report. It is a measurement, not a fix.

## Are these detectors real?

${r.selfTestDetectors} detectors run. Before every real measurement the harness
renders a page carrying one deliberate instance of each defect and requires
every detector to fire; if any stays silent the run aborts rather than emit a
green report. That check has already paid for itself — it caught that the
horizontal-overflow detector could never fire (the page sets \`overflow: hidden\`
to emulate a device, so \`scrollWidth\` is clamped and the check was dead on all
${r.screens.length} screens), and that truncation was being measured on the wrong axis.

## What is measured

| Property | How |
|---|---|
| Horizontal overflow | Widest box's edge against the viewport, per width |
| Cropped cards | Any box extending past either viewport edge by >0.5px |
| Clipped text | A leaf whose content is cut by \`overflow: hidden\` with no clamp |
| Truncated typography | A leaf whose \`-webkit-line-clamp\` has engaged — truncation the screen asked for |
| Wrapped buttons | A control's label height against its own line box |
| Touch targets | Interactive roles measured against the ${r.tapFloor}pt floor |
| Broken hierarchy | Count of accent-filled dominant controls, and whether it changes with width |
| Layout shifts | Reading order (RTL, row-bucketed) compared against ${r.reference}pt |
| Inconsistent spacing | Computed gaps and padding against the 4pt rhythm |
| RTL regressions | Root direction, stray \`ltr\` runs carrying no Latin, back control's edge |

## What is NOT measured

A green tick above means the property was checked. These were not, and no tick
should be read as covering them.

${r.unmeasured.map(([k, why]) => `- **${k}** — ${why}`).join("\n")}

## Result by screen

| Screen state | Verdict | Findings |
|---|---|---|
${rows}

${detail ? `## Findings\n\n${detail}` : "Every screen state passed at every width.\n"}
## Content height by width

A height that grows as the viewport narrows is a reflow doing its job. A height
that does not move at all across ${r.widths[0]}–${r.widths[r.widths.length - 1]}pt means nothing about the layout
responds to width — worth knowing before implementation starts.

| Screen state | ${r.widths.map((w) => `${w}pt`).join(" | ")} |
|---|${r.widths.map(() => "---").join("|")}|
${heightTable}
`;

writeFileSync(join(OUT, "RESPONSIVE_REPORT.md"), md, "utf8");
console.log(`\nResponsive report\n`);
console.log(`  RESPONSIVE_REPORT.md    ${r.pass} pass · ${r.minor} minor · ${r.fail} fail`);
console.log(`  ${r.selfTestDetectors} detectors proved · ${r.unmeasured.length} propert(ies) declared unmeasured\n`);
