/* ============================================================
   PRODUCT CATALOG DATA
   Add / edit products here. Every field on the product page is
   driven by this file — no HTML edits needed to add a product.
   ============================================================ */

const STORE_CONFIG = {
  name: "CarePlus Pharmacy",
  // WhatsApp number in international format, digits only (no +, no spaces)
  whatsappNumber: "9647700000000",
  currency: "IQD",
  tagline: "Your trusted health & wellness partner",
};

const PRODUCTS = [
  {
    id: "vitamin-c-1000",
    name: "Vitamin C 1000mg Effervescent",
    brand: "NutraWell",
    category: "Vitamins & Supplements",
    price: 12000,
    badge: "Best Seller",
    rating: 4.8,
    reviewCount: 132,
    images: ["🍊", "💊", "📦"],
    summary: "High-strength vitamin C in a refreshing orange-flavored effervescent tablet to support immunity and energy.",
    description: "NutraWell Vitamin C 1000mg delivers a full daily dose of vitamin C in a fast-absorbing effervescent format. Each tube contains 20 tablets that dissolve into a pleasant orange drink. Ideal for daily immune support, during cold season, or periods of fatigue and stress.",
    benefits: [
      "Supports a healthy immune system",
      "Contributes to normal collagen formation for skin",
      "Reduces tiredness and fatigue",
      "Powerful antioxidant protection",
    ],
    ingredients: ["Ascorbic acid (Vitamin C) 1000mg", "Citric acid", "Sodium bicarbonate", "Natural orange flavor", "Sweetener (sucralose)"],
    usage: "Dissolve one tablet in a glass of water (200ml) once daily, preferably with a meal. Do not exceed the recommended dose.",
    suitableFor: ["Adults and children over 12", "People with weak immunity", "Smokers (higher vitamin C needs)", "Active lifestyles"],
    warnings: ["Contains sodium — consult your doctor if on a low-sodium diet", "Not a substitute for a varied diet", "Keep out of reach of children"],
    faqs: [
      { q: "Can I take it every day?", a: "Yes, one tablet daily is safe for most adults. Long-term daily use is fine within the recommended dose." },
      { q: "When is the best time to take it?", a: "Morning with breakfast is ideal — vitamin C can be mildly energizing." },
      { q: "Is it suitable during pregnancy?", a: "Consult your doctor or our pharmacist via WhatsApp before use during pregnancy." },
    ],
    related: ["zinc-plus", "multivit-daily", "omega3-fish-oil"],
    alternatives: ["multivit-daily"],
    frequentlyBoughtWith: ["zinc-plus"],
    reviews: [
      { name: "Sara A.", stars: 5, text: "Great taste and I felt the difference in my energy within a week." },
      { name: "Mohammed K.", stars: 5, text: "My whole family takes it during winter. Fast delivery via WhatsApp order." },
    ],
    tags: ["immunity", "vitamin c", "energy", "cold"],
  },
  {
    id: "zinc-plus",
    name: "Zinc Plus 25mg Tablets",
    brand: "NutraWell",
    category: "Vitamins & Supplements",
    price: 9000,
    badge: "Pharmacist Pick",
    rating: 4.7,
    reviewCount: 84,
    images: ["🛡️", "💊"],
    summary: "Daily zinc supplement to strengthen immunity, support skin health, and aid recovery.",
    description: "Zinc Plus provides 25mg of highly absorbable zinc gluconate per tablet. Zinc is essential for immune function, wound healing, skin clarity, and normal taste and smell. A perfect partner to vitamin C during cold season.",
    benefits: ["Strengthens immune defense", "Supports clear, healthy skin", "Aids wound healing", "Supports normal hair and nails"],
    ingredients: ["Zinc gluconate (25mg elemental zinc)", "Microcrystalline cellulose", "Magnesium stearate"],
    usage: "Take one tablet daily after food. Avoid taking on an empty stomach.",
    suitableFor: ["Adults", "People with frequent colds", "Acne-prone skin", "Vegetarians (plant-based diets are often low in zinc)"],
    warnings: ["May cause nausea if taken without food", "Do not exceed 40mg zinc per day from all sources"],
    faqs: [
      { q: "Can I take zinc with vitamin C?", a: "Yes — they work well together for immunity. Many customers buy them as a pair." },
      { q: "How long until I see skin benefits?", a: "Most people notice improvement after 4–6 weeks of consistent use." },
    ],
    related: ["vitamin-c-1000", "multivit-daily"],
    alternatives: ["multivit-daily"],
    frequentlyBoughtWith: ["vitamin-c-1000"],
    reviews: [{ name: "Zainab H.", stars: 5, text: "Helped my skin a lot. The pharmacist recommended it with vitamin C." }],
    tags: ["immunity", "skin", "zinc"],
  },
  {
    id: "multivit-daily",
    name: "Daily Multivitamin Complete",
    brand: "VitaCore",
    category: "Vitamins & Supplements",
    price: 18000,
    badge: "",
    rating: 4.6,
    reviewCount: 67,
    images: ["🌈", "💊", "📦"],
    summary: "23 essential vitamins and minerals in one convenient daily tablet.",
    description: "Daily Multivitamin Complete covers your nutritional bases with 23 vitamins and minerals at optimal doses, including vitamin D3, B-complex, iron, and magnesium. One tablet a day fills the gaps in a busy modern diet.",
    benefits: ["Covers daily vitamin and mineral needs", "Supports energy metabolism", "Includes vitamin D3 for bones and immunity", "Iron for healthy blood"],
    ingredients: ["Vitamins A, C, D3, E, K, B-complex", "Iron, Zinc, Magnesium, Selenium, Iodine", "Calcium carbonate"],
    usage: "One tablet daily with breakfast.",
    suitableFor: ["Busy adults", "Students", "Anyone with an irregular diet"],
    warnings: ["Contains iron — keep away from children", "Not recommended alongside other iron supplements without medical advice"],
    faqs: [{ q: "Is this instead of vitamin C and zinc?", a: "It contains both at moderate doses. For targeted immune support during illness, dedicated vitamin C + zinc is stronger." }],
    related: ["vitamin-c-1000", "zinc-plus", "omega3-fish-oil"],
    alternatives: ["vitamin-c-1000"],
    frequentlyBoughtWith: ["omega3-fish-oil"],
    reviews: [{ name: "Ali R.", stars: 4, text: "Convenient — one tablet covers everything." }],
    tags: ["multivitamin", "energy", "daily"],
  },
  {
    id: "omega3-fish-oil",
    name: "Omega-3 Fish Oil 1000mg",
    brand: "VitaCore",
    category: "Vitamins & Supplements",
    price: 22000,
    badge: "Trending",
    rating: 4.9,
    reviewCount: 98,
    images: ["🐟", "💛"],
    summary: "Pure fish oil rich in EPA & DHA for heart, brain, and joint health.",
    description: "Molecularly distilled fish oil softgels delivering 1000mg omega-3 with high EPA/DHA content. Supports cardiovascular health, cognitive function, healthy vision, and joint comfort. Burp-free coated capsules.",
    benefits: ["Supports heart health", "Promotes brain function and focus", "Eases joint stiffness", "Supports eye health"],
    ingredients: ["Fish oil concentrate 1000mg (EPA 330mg, DHA 220mg)", "Gelatin capsule", "Vitamin E (antioxidant)"],
    usage: "Take 1–2 softgels daily with meals.",
    suitableFor: ["Adults concerned with heart health", "Students and knowledge workers", "People who eat little fish"],
    warnings: ["Consult your doctor if taking blood thinners", "Not suitable for fish allergy"],
    faqs: [{ q: "Does it have a fishy aftertaste?", a: "No — the capsules are enteric-coated to prevent fishy burps." }],
    related: ["multivit-daily", "vitamin-c-1000"],
    alternatives: ["multivit-daily"],
    frequentlyBoughtWith: ["multivit-daily"],
    reviews: [{ name: "Dr. Hasan", stars: 5, text: "High quality EPA/DHA ratio. I recommend it to my patients." }],
    tags: ["heart", "brain", "omega 3", "joints"],
  },
  {
    id: "hydra-face-cream",
    name: "HydraDerm Intensive Face Cream",
    brand: "DermaLine",
    category: "Skin Care",
    price: 25000,
    badge: "Best Seller",
    rating: 4.8,
    reviewCount: 156,
    images: ["🧴", "✨"],
    summary: "Deep hydration with hyaluronic acid and ceramides for dry and sensitive skin.",
    description: "HydraDerm combines three molecular weights of hyaluronic acid with skin-identical ceramides to restore the moisture barrier. Fragrance-free, non-comedogenic, and clinically tested on sensitive skin. Visible plumping from first use.",
    benefits: ["48-hour deep hydration", "Repairs the skin moisture barrier", "Reduces fine lines caused by dryness", "Soothes redness and irritation"],
    ingredients: ["Hyaluronic acid complex", "Ceramides NP, AP, EOP", "Niacinamide 2%", "Glycerin", "Shea butter"],
    usage: "Apply morning and evening on clean skin. Massage gently until absorbed. Suitable under makeup and sunscreen.",
    suitableFor: ["Dry and dehydrated skin", "Sensitive skin", "All ages"],
    warnings: ["For external use only", "Avoid direct contact with eyes", "Patch-test if you have very reactive skin"],
    faqs: [
      { q: "Is it suitable for oily skin?", a: "Yes — it's non-comedogenic, but oily skin types may prefer using it only at night." },
      { q: "Can I use it with retinol?", a: "Yes, apply it after retinol to reduce irritation." },
    ],
    related: ["sun-shield-spf50", "gentle-cleanser"],
    alternatives: ["gentle-cleanser"],
    frequentlyBoughtWith: ["sun-shield-spf50"],
    reviews: [
      { name: "Noor S.", stars: 5, text: "My skin has never felt this soft. Ordered twice already via WhatsApp." },
      { name: "Rania M.", stars: 5, text: "Perfect for my sensitive skin, no breakouts." },
    ],
    tags: ["moisturizer", "dry skin", "hyaluronic", "sensitive"],
  },
  {
    id: "sun-shield-spf50",
    name: "SunShield SPF50+ Invisible Fluid",
    brand: "DermaLine",
    category: "Skin Care",
    price: 28000,
    badge: "Pharmacist Pick",
    rating: 4.9,
    reviewCount: 201,
    images: ["☀️", "🧴"],
    summary: "Ultra-light invisible sunscreen with SPF50+ — no white cast, no greasy feel.",
    description: "A featherweight fluid sunscreen offering very high UVA/UVB protection. Its invisible finish works on all skin tones and sits perfectly under makeup. Water-resistant and enriched with antioxidants against pollution damage.",
    benefits: ["SPF50+ very high protection", "Zero white cast", "Prevents dark spots and premature aging", "Water and sweat resistant"],
    ingredients: ["UVA/UVB filter complex", "Vitamin E", "Glycerin", "Lightweight silicone base"],
    usage: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours, and after swimming or sweating.",
    suitableFor: ["All skin types and tones", "Daily urban use", "Beach and outdoor activities"],
    warnings: ["Avoid the eye area", "Reapplication is essential for stated protection"],
    faqs: [{ q: "Can I use it daily under makeup?", a: "Yes — the invisible fluid texture is designed exactly for that." }],
    related: ["hydra-face-cream", "gentle-cleanser"],
    alternatives: [],
    frequentlyBoughtWith: ["hydra-face-cream"],
    reviews: [{ name: "Huda J.", stars: 5, text: "Finally a sunscreen with no white cast! Holy grail." }],
    tags: ["sunscreen", "spf", "protection", "anti-aging"],
  },
  {
    id: "gentle-cleanser",
    name: "PureBalance Gentle Facial Cleanser",
    brand: "DermaLine",
    category: "Skin Care",
    price: 15000,
    badge: "",
    rating: 4.7,
    reviewCount: 73,
    images: ["🫧", "🧴"],
    summary: "Soap-free gel cleanser that removes impurities without stripping the skin.",
    description: "A pH-balanced, soap-free cleansing gel that lifts away dirt, oil, and light makeup while preserving the skin barrier. With soothing panthenol and glycerin, skin feels clean, calm, and never tight.",
    benefits: ["Cleans without dryness or tightness", "Maintains healthy skin pH", "Soothes with panthenol", "Suitable for daily use, morning and night"],
    ingredients: ["Mild surfactant complex", "Panthenol (Pro-Vitamin B5)", "Glycerin", "Chamomile extract"],
    usage: "Massage a small amount onto damp skin, rinse with lukewarm water. Use morning and evening.",
    suitableFor: ["All skin types", "Sensitive and acne-prone skin"],
    warnings: ["External use only", "If irritation occurs, discontinue use"],
    faqs: [{ q: "Does it remove makeup?", a: "It removes light makeup; for heavy makeup use a micellar water first." }],
    related: ["hydra-face-cream", "sun-shield-spf50"],
    alternatives: [],
    frequentlyBoughtWith: ["hydra-face-cream"],
    reviews: [{ name: "Aya T.", stars: 5, text: "So gentle, my skin stopped feeling tight after washing." }],
    tags: ["cleanser", "sensitive", "daily routine"],
  },
  {
    id: "baby-rash-cream",
    name: "BabySoft Diaper Rash Cream",
    brand: "TinyCare",
    category: "Mother & Baby",
    price: 11000,
    badge: "Trending",
    rating: 4.9,
    reviewCount: 189,
    images: ["👶", "🧴"],
    summary: "Zinc oxide barrier cream that soothes and prevents diaper rash from the first change.",
    description: "BabySoft creates a breathable protective barrier with 15% zinc oxide, calming irritated skin and preventing new rashes. Enriched with panthenol and calendula, free from fragrance, parabens, and dyes. Pediatrician approved.",
    benefits: ["Soothes redness within hours", "Protective barrier against wetness", "Fragrance-free and hypoallergenic", "Safe from day one"],
    ingredients: ["Zinc oxide 15%", "Panthenol", "Calendula extract", "Petrolatum", "Beeswax"],
    usage: "Apply a thick layer at every diaper change, especially before sleep. Clean and dry the area first.",
    suitableFor: ["Newborns and babies", "Also useful for adult skin chafing"],
    warnings: ["External use only", "Consult a doctor if rash worsens or persists beyond 7 days"],
    faqs: [
      { q: "How often should I apply it?", a: "At every diaper change for active rash, or once daily for prevention." },
      { q: "Is it safe for newborns?", a: "Yes — it's formulated to be safe from the first day of life." },
    ],
    related: ["baby-shampoo"],
    alternatives: [],
    frequentlyBoughtWith: ["baby-shampoo"],
    reviews: [{ name: "Um Yusuf", stars: 5, text: "The rash disappeared overnight. Every mother needs this." }],
    tags: ["baby", "diaper rash", "zinc oxide"],
  },
  {
    id: "baby-shampoo",
    name: "TinyCare No-Tears Baby Shampoo",
    brand: "TinyCare",
    category: "Mother & Baby",
    price: 9500,
    badge: "",
    rating: 4.8,
    reviewCount: 92,
    images: ["🛁", "👶"],
    summary: "Ultra-mild no-tears shampoo and body wash for delicate baby skin and hair.",
    description: "A 2-in-1 gentle wash for hair and body, formulated at the same pH as baby tears so bath time stays happy. With oat extract to protect delicate skin. No sulfates, no parabens, no dyes.",
    benefits: ["No tears, no stinging eyes", "2-in-1 hair and body", "Protects the natural skin barrier", "Hypoallergenic"],
    ingredients: ["Ultra-mild coconut-derived cleansers", "Oat extract", "Glycerin"],
    usage: "Apply to wet hair and body, lather gently, rinse. Suitable for daily use.",
    suitableFor: ["Newborns and up", "Sensitive and eczema-prone baby skin"],
    warnings: ["External use only"],
    faqs: [{ q: "Can adults with sensitive skin use it?", a: "Absolutely — many parents end up using it themselves." }],
    related: ["baby-rash-cream"],
    alternatives: [],
    frequentlyBoughtWith: ["baby-rash-cream"],
    reviews: [{ name: "Um Lina", stars: 5, text: "Bath time is finally tear-free!" }],
    tags: ["baby", "shampoo", "gentle"],
  },
  {
    id: "pain-relief-gel",
    name: "FlexEase Muscle & Joint Gel",
    brand: "MediRelief",
    category: "Pain Relief",
    price: 13500,
    badge: "",
    rating: 4.6,
    reviewCount: 58,
    images: ["💪", "🧴"],
    summary: "Fast-acting cooling gel for muscle aches, back pain, and joint stiffness.",
    description: "FlexEase combines menthol's immediate cooling with anti-inflammatory botanical extracts for relief of muscle soreness, sports strains, back pain, and joint stiffness. Non-greasy and fast-absorbing.",
    benefits: ["Cooling relief within minutes", "Eases post-workout soreness", "Soothes back and neck tension", "Non-greasy formula"],
    ingredients: ["Menthol 5%", "Camphor", "Arnica extract", "Eucalyptus oil"],
    usage: "Massage a thin layer onto the affected area 2–3 times daily. Wash hands after use.",
    suitableFor: ["Adults with muscle/joint discomfort", "Athletes", "Desk workers with neck/back tension"],
    warnings: ["Do not apply to broken skin", "Avoid eyes and mucous membranes", "Not for children under 12"],
    faqs: [{ q: "Can I use it with a heating pad?", a: "No — never combine with external heat, it can irritate the skin." }],
    related: ["omega3-fish-oil"],
    alternatives: [],
    frequentlyBoughtWith: ["omega3-fish-oil"],
    reviews: [{ name: "Karim D.", stars: 5, text: "Works within minutes on my lower back." }],
    tags: ["pain", "muscle", "joints", "gel"],
  },
];
