/**
 * The technical debt register.
 *
 * Debt is only real if it is visible and owned. Every item carries an impact,
 * a priority, an owner and the slice that will resolve it. An item leaves this
 * register by being FIXED — never by being quietly deleted, which is why each
 * resolved item stays with its resolution recorded.
 */

export const DEBT = [
  {
    id: "TD-1",
    description: "The patient app has no DEVICE build and no BACKEND. A host now exists: `apps/patient/web` implements the `Host` interface against browser globals — a clock, crypto ids, navigator.onLine, localStorage, setTimeout — and mounts the composition root through react-native-web, so the application has been started and used in a page for the first time. A dev server (`tools/devserver`) answers the declared v1 contracts beside it. Neither is production: react-native-web is not React Native, so no phone has run this, and the dev server invents DATA (nine catalogue rows, three branches) to exercise BEHAVIOUR the contracts already declare — it is not a backend. No session token is stored or refreshed, and deviceId/baseUrl still have no production source.",
    impact: "The loop can now be walked by a person rather than only by a test suite, which is how the E4 navigation defect was found. What remains unexercised is everything a device and a server bring: native gestures, platform chrome, safe-area insets and keyboard avoidance are untested because no React Native project exists, and real latency, pagination, token refresh, TLS and server-side authorization are untested because nothing behind the port is real.",
    priority: "critical",
    owner: "platform-foundation",
    slice: "Stage 5 — Infrastructure",
    status: "open",
  },
  {
    id: "TD-2",
    description: "Screenshots are DOM renders of the real component tree, not device captures.",
    impact: "Layout, hierarchy, typography, colour, spacing and tap targets are verified. Native gestures, platform chrome, safe-area insets, keyboard avoidance and animation are NOT.",
    priority: "high",
    owner: "patient-app",
    slice: "Whenever a device build first runs",
    status: "open",
  },
  {
    id: "TD-3",
    description: "SCREEN transitions are not implemented; element-level motion is. This item used to say no transition existed at all, which was wrong and understated the code while overstating the gap: `Enter`, `Pulse` and `Shake` are real Animated components with native-driver and reduced-motion support, and they are used on eight call sites. What has no consumer is navigation. Measured: 13 motion tokens are declared and 2 are spent — `errorShake` and `offerArrival`. The other 11 include every one that describes moving between screens — screenPush, sheetPresent, sheetDrag — so the app root swaps a component per `state.screen` with nothing in between.",
    impact: "Going from a request to the sign-in ask, or from the wait to the offers, is a cut rather than a movement, and §27 says each of those tokens TEACHES something — screenPush teaches where you are in the hierarchy, sheetPresent teaches that a thing is temporary and layered above. Losing that is losing the one cue that tells a patient whether they went deeper or sideways. Within a screen the product already moves: a field shakes when it is wrong, content enters, a countdown pulses.",
    priority: "high",
    owner: "patient-app",
    slice: "Next polish pass",
    status: "open",
  },
  {
    id: "TD-21",
    description: "Offers reach the patient by POLLING, not by being told. §8 says the patient is notified when pharmacies reply; a notification needs push, which a browser build cannot receive and a device build does not exist to (TD-1, TD-2). The composition root therefore re-reads GET /v1/requests/{id} every three seconds while any branch is still thinking, and stops when none is.",
    impact: "Behaviourally equivalent above the port — the same intents arrive from the same contract, so no screen and no reducer can tell the difference — and materially different below it. The app must be OPEN and on screen for an offer to arrive, so a patient who locks their phone during a four-hour window learns nothing until they look; and a twenty-minute window costs hundreds of requests and the battery to make them, on the phones and networks this product is for. It is a stand-in for the notification channel, not the design.",
    priority: "high",
    owner: "notification-service",
    slice: "Device build — push notifications",
    status: "open",
  },
  {
    id: "TD-20",
    description: "R7's «ألغِ الطلب» does not cancel anything: the screen contract declares it as a secondary leading to S1, so pressing it dispatches `open S1` and nothing else — no intent, no call, no transition. The request stays broadcast to every pharmacy that was asked. TWO CORRECTIONS to this item, both recorded rather than overwritten. It first said the behaviour was unstated and therefore blocked; that read only the screen contract and was wrong — `POST /v1/requests/{id}/cancel` is declared in the API model (§4 R7 — 200 { request }, 404 not_found_or_not_yours, 409 already_accepted). It then said the client half was buildable; that was wrong too, and this is the real finding: the API contract and the §6 state machine DISAGREE. A patient on R7 is in `broadcast` or `answered`, and the Request machine has no outgoing edge for a cancellation from either. Its only two are `cancelFromOutbox` (queued → draft, D27 — a request that never left the device) and `abandon` (unanswered or partially_filled → closed). The domain model agrees with the machine and not the endpoint: it lists eight Request states and the producer of each, and no state is produced by that route.",
    impact: "A control that states an outcome and produces none, on a live request other people are working on — a patient who wants to stop a request believes they have. It cannot be built: calling the endpoint would return a request in a state the client has no edge to reach, and adding that edge is inventing a state transition, which Rule 5 and the forbidden list both refuse. This is not a gap in the Blueprint but a contradiction between two frozen documents, and it needs one of them to move: either §6 gains the transition, or §4 R7 loses the control.",
    priority: "high",
    owner: "marketplace-engine",
    slice: "Blocked — the API contract and the §6 machine disagree",
    status: "open",
  },
  {
    id: "TD-22",
    description: "The Arabic plural forms are engineering's reading of the grammar, not a native speaker's or the copywriter's. `plural`/`counted` encode the four CLDR categories and every counted string in the app now selects through them, which fixes what was unambiguously wrong — «١ دقائق», «٢ محاولات», «٥ دقيقة». What is NOT verified is the dialect: this product is written in Iraqi Arabic, and some inflections have a colloquial form that differs from Modern Standard — the dual «دوائين», the non-human plural agreement in «٣ أدوية تحتاج وصفة», and «اثنين غيرهم» on the outbox label are the three worth a second pair of eyes.",
    impact: "Strictly better than what shipped, and not yet confirmed. Nothing here changes what a screen SAYS, only how the number agrees with it, so the risk is a phrase that reads as slightly formal rather than one that misinforms. It needs a native Iraqi reader — ideally the person who wrote the original copy — to confirm the four forms for each noun. Until then the register carries this rather than the tests implying it was reviewed.",
    priority: "medium",
    owner: "patient-app",
    slice: "Next copy review",
    status: "open",
  },
  {
    id: "TD-23",
    description: "R7 does not end. Its dial now counts down for real — before the clock ticked, nobody would have watched it reach zero — and at zero it shows «٠» beside «الوقت الباقي على نافذة الردود» and goes on saying «انرسل — ننتظر الردود» indefinitely. The screen's own copy promises the opposite: «إذا خلصت بدون رد، نكلّك الصدك ونقترح شنو تسوي». Nothing fires `windowElapsed`, so the request stays `broadcast` in state forever.",
    impact: "The promise R7 makes about what happens when nobody answers is not kept, on the screen whose entire job is making a wait legible. The store half is declared and buildable — §6 has `broadcast --windowElapsed--> unanswered` and `request.unanswered` is a registered event — but the screen it leads to is R11, whose design package entry reads «OPEN to the designer: Everything. Not rendered.» Moving the request with nowhere to land would change the state and nothing a patient can see, so the state is left honest rather than moved into a screen that does not exist. The polling itself now stops at the window (it did not before), so this costs a patient a broken promise rather than a battery.",
    priority: "high",
    owner: "patient-app",
    slice: "Blocked — R11 is undesigned",
    status: "open",
  },
  {
    id: "TD-24",
    description: "R1's declared guards and §3.1 contradict each other, and the implementation resolves it by walking around the guard. The Blueprint gives R1 the permission \"authenticated, subject with Order scope or self or guardian\" and the guard set `requireSession · requireOrderScope · blockMemorialised`. §3.1 forbids a sign-in wall and requests the account at the first action that NEEDS one, and D26 preserves the interrupted work — E4 is drawn showing «طلبك محفوظ: أموكسيسيلين + باراسيتامول», a draft that only a GUEST could have built. Both cannot hold: if R1 needs a session, no guest can assemble the request E4 promises to keep. Today `addItem` calls `navigate` rather than `open`, so it never asks the guards, and that bypass is the only reason the product works end to end.",
    impact: "A guard that one path enforces and another does not is not a guard (§5 rule 1), and the same screen answers differently depending on how you arrive. It is visible: R2's «اكتب الاسم بدال الصورة» goes through the declared exit `leadsTo: R1`, `open` runs the guards, and a guest is sent to sign in by a control that offered to let them type instead — walked in a browser. Fixing the symptom would mean routing that control around the guard as well, which is weakening a rule to make code pass rather than resolving the contradiction. It needs one of the two documents to move: either R1 loses `requireSession`, or §3.1 and D26 say where a guest assembles a draft instead.",
    priority: "high",
    owner: "patient-app",
    slice: "Blocked — R1's guards and §3.1 disagree",
    status: "open",
  },
  {
    id: "TD-25",
    description: "E8 has no declared treatment for a save that could not be MADE. Its Blueprint row declares `error` («ما اخترت منطقة») and `permissionRefused`, and its offline rule is that the district list is bundled — which is true of the list and not of the submit: finishing onboarding is a PATCH /v1/me, and that call can fail on a network rather than be refused by a server.",
    impact: "Today the control returns from busy and says nothing, so a patient on a bad connection presses «خلص» and watches it do nothing twice. The alternative available without a decision is worse: the first version of this code answered a dropped connection with DISTRICT_REQUIRED, which words as «ما اخترت منطقة» — telling a patient who DID choose a district that they had not. Blaming someone for a network is the one thing this screen must not do, so it asserts nothing instead. Needs a sentence for «ما كدرنا نحفظ — جرّب مرة ثانية», which is copy and not engineering's to write.",
    priority: "medium",
    owner: "patient-app",
    slice: "Blocked — needs a failure sentence for E8",
    status: "open",
  },
  {
    id: "TD-27",
    description: "S1 cannot tell §22's two empties apart from anything but the CURRENT SESSION. The Blueprint gives Today active reservations AND dispense history, scoped to the active subject; this build has a port for neither — the reservation Today reads is the one held in memory since launch, and V8 (dispense history) is not contracted. So `fromReservation(null)` answers `new`, and a returning patient who collected a prescription last week is greeted by the teaching empty rather than by «كل شي تمام». Two further Blueprint facts are absent for the same reason: the subject switcher (S2) and the history list (V8) are declared exits that `isBuilt` drops, so Today shows one subject's reservation and never says whose.",
    impact: "The wrong empty, in the SAFE direction, and deliberately so: being taught something you already know costs a patient nothing, while «ما عندك شي يحتاج انتباهك» in front of someone whose hold we failed to load tells them to stay home while their medicine goes back on the shelf. Nothing here is a guess about product behaviour — the states, their words and their actions are all declared, and what is missing is data. It resolves with the reads behind S1 (GET /v1/me for the subject, the dispense history for V8), not with a decision.",
    priority: "high",
    owner: "patient-app",
    slice: "Stage 5 — Infrastructure",
    status: "open",
  },
  {
    id: "TD-17",
    description: "The bundled district list contains four Baghdad districts with `covered` set on three of them. E8's Blueprint row fixes the SHAPE — the list is bundled, location is never requested, an uncovered district is shown honestly rather than hidden (E12) — but Blueprint v3 carries no coverage map, so the contents are the four districts E8 has been drawn and reviewed against since it was designed.",
    impact: "Nothing in the app hard-codes an id from the list and the real one replaces the file wholesale, so this cannot leak into logic. It does mean a patient in a district Dawai actually serves may not find it, and the coverage claim on each row is not yet a claim product has made. Needs the coverage list as a product input.",
    priority: "medium",
    owner: "patient-app",
    slice: "Blocked — needs the coverage list",
    status: "open",
  },

  {
    id: "TD-10",
    description: "The Night Mint delivery is dark-only. Its daylight sibling palette is not designed, so the patient app forces dark and ignores the device's light preference.",
    impact: "Users who run their phone in light mode get a dark app. `patientLight` is currently an alias of `patientDark` so nothing renders half-designed, which means the contrast gate cannot catch a light-scheme regression either.",
    priority: "high",
    owner: "design",
    slice: "When the daylight palette is delivered",
    status: "open",
  },
  {
    id: "TD-11",
    description: "V2's code-panel caption ships at #63726B, not the delivered #6B7A74, because the designer's value measures 4.10:1 on #F7F4EE — below the 4.5 body floor.",
    impact: "A one-value deviation from the delivery, on the screen Blueprint v3 says must never fail. Reverts the moment Design confirms a replacement.",
    priority: "medium",
    owner: "design",
    slice: "Next design round",
    status: "open",
  },
  {
    id: "TD-6",
    description: "V2's freshness is hard-coded live because nothing is cached yet.",
    impact: "The cached-countdown path is implemented and photographed but never exercised against real cache eviction.",
    priority: "medium",
    owner: "patient-app",
    slice: "Stage 5 — Infrastructure",
    status: "open",
  },
  {
    id: "TD-7",
    description: "Performance is entirely unmeasured — startup, render, navigation latency, memory and bundle size.",
    impact: "No regression can be detected. The dashboard reports these as NOT VERIFIED rather than green.",
    priority: "medium",
    owner: "platform-foundation",
    slice: "Once a device build exists",
    status: "partially addressed",
    note: "Module count and source size are now measured; runtime metrics remain unverifiable without a device build.",
  },
  {
    id: "TD-8",
    description: "The store held a `requested` variable computed from the submission and then discarded it, because request line ids are minted by the server and the client has none yet.",
    impact: "Acceptance is computed against the offer's own line ids rather than the request's. Correct today because they are the same fixture, and wrong the moment a real server assigns ids.",
    priority: "high",
    owner: "marketplace-engine",
    slice: "Stage 5 — Infrastructure",
    status: "open",
  },
  {
    id: "TD-12",
    description: "ActionCard sets accessibilityLabel on the Pressable, which makes the card ONE accessibility element on both platforms: the label is announced and the children are not. On R8 an offer card therefore reads as «افتح عرض صيدلية الرشيد» alone — the price, the coverage («يغطي ٢ من ٢»), the substitution flag, the distance and the honoured band are all rendered and none of them is spoken. On F2 a result reads as «أضف بانادول للطلب», dropping the strength, the form, the Latin name and the price.",
    impact: "A patient using TalkBack or VoiceOver makes the most consequential decision in the product — which pharmacy to reserve from — without hearing anything the decision is based on. The visible card and the spoken card are different products. The engineering defect is clear; the fix is not, because what an offer card should announce, in which order, in Iraqi Arabic, is a content decision. §25 and the Blueprint state no spoken-content rule for a composite card, so implementation must not invent one. Blocked on a product/design answer, not on code.",
    priority: "high",
    owner: "patient-app",
    slice: "Blocked — needs a spoken-content decision for composite cards",
    status: "open",
  },
  {
    id: "TD-13",
    description: "Offline.cancel refuses silently while an item is in flight. It returns the outbox object unchanged (identical by reference) when state is \"sending\", so the reducer stores the same value, the screen re-renders identically, and the patient's cancel produces no signal of any kind. With DEFAULT_POLICY the retry loop holds an item in \"sending\" for roughly 30 seconds of backoff across six attempts, and flush only re-reads the live outbox BETWEEN items, never between retries.",
    impact: "For up to half a minute after pressing send, R13's cancel does nothing and says nothing. The comment in flush.ts names this exact failure — 'the user\'s cancel does nothing but move a label' — and guards against it at the item boundary, which is not where the waiting happens. Whether a request already on the wire SHOULD be cancellable is a product decision (§21 · D27 · R13): a POST that may already have been accepted cannot simply be dropped, and the honest options — refuse visibly, or cancel and reconcile against the idempotency key — differ in what the patient is promised. The engineering half is unambiguous and unblocked: a function that can refuse must say so rather than returning its input.",
    priority: "medium",
    owner: "platform-foundation",
    slice: "Blocked — needs a product answer on cancelling in-flight writes",
    status: "open",
  },
  {
    id: "TD-14",
    description: "V2 renders two controls that do nothing. The contract declares a primary «الاتجاهات» and a secondary «اتصال بالصيدلية», ReservationScreen draws both, and App.tsx wires both to `noop` — there is no maps handoff and no dialer. The rendered review page V2-held.html contains both labels. A third declared secondary, «ألغِ الحجز» → V5, is not rendered at all: `onCancel` is passed from App.tsx as `() => onAction(\"V5\")`, which `isBuilt` silently drops because V5 is not in this build, and ReservationScreen never uses the prop.",
    impact: "§4 calls V2 the screen that must never fail, and it is the screen a patient stands in front of a pharmacy holding. Two of its three actions are inert: tapping «الاتجاهات» or «اتصال بالصيدلية» does nothing at all, with no message and no fallback — the exact defect the isBuilt filter exists to prevent, in the one category isBuilt cannot express, because a dialer and a map are device capabilities rather than screens. Whether to wire them, disable them with a stated reason, or drop them until a device build exists is a product and platform decision (§4 V2 · TD-1 · TD-2), so it is registered rather than answered here. The dead `onCancel` prop is separate and smaller: it makes the cancel path look wired when V5 does not exist.",
    priority: "high",
    owner: "patient-app",
    slice: "Blocked — needs a device build and a decision on inert declared controls",
    status: "open",
  },
  {
    id: "TD-15",
    description: "A screen can be opened without the state it needs. `open` runs the route guards and `isBuilt`, neither of which knows that V2 without a reservation, R9 without an offer, or R3 without a capture has nothing to draw. Dispatching { kind: \"open\", screen: \"V2\" } on a signed-in state with reservation: null navigates there and renders the Placeholder. App.tsx claimed the reducer prevented this; it does not.",
    impact: "S1 has now landed, and this did NOT become reachable through it, which the previous version of this item predicted it would. Today draws the control into V2 from the reservation it is holding — no hold, no control — so the one declared exit into V2 cannot be taken while there is nothing behind it. What remains is D26's replay of a pending screen, and the raw intent, neither of which any rendered control produces. The underlying question is unchanged and still a product one: what a patient should see when the reservation behind V2 is gone (§4 V2 says the reservation lives on Today, but that is back behaviour, not a fallback), so no redirect has been invented. The Placeholder is honest about the failure and is still a screen nobody designed.",
    priority: "medium",
    owner: "patient-app",
    slice: "Blocked — needs a product answer",
    status: "partially addressed",
    note: "S1 landed without opening the path this predicted, because Today derives its exit into V2 from the hold it holds rather than rendering it unconditionally.",
  },
  {
    id: "TD-16",
    description: "Nothing bounds the pack count on a request line. `Marketplace.packs` refuses zero, negatives and non-integers and accepts everything else — 1,000,000 packs is ACCEPTED, verified by probe. `draft.setPacks` and `draft.add` pass the value straight through, and DraftScreen's stepper increments without a ceiling, so a patient holding the + button sends whatever number they reach to every eligible pharmacy.",
    impact: "§2 fixes the maximum LINES per request at 8 and the module's own docstring says the review's central finding was that v1 'left every load-bearing quantity undefined'. The quantity per line is such a quantity and Blueprint v3 does not state it, so there is nothing to implement: any ceiling chosen here would be an invented business rule, which Rule 3 and the forbidden list both refuse. The consequence is real but bounded — a pharmacy receives an absurd request and refuses it, which costs a pharmacist's attention rather than a patient's safety. Needs a number from product, after which it belongs beside MAX_REQUEST_LINES in marketplace/rules.ts.",
    priority: "low",
    owner: "marketplace-engine",
    slice: "Blocked — needs a Blueprint quantity",
    status: "open",
  },
];

/** Debt that has been paid. Kept, with how it was resolved, so the register
 *  records a history rather than only a backlog. */
export const RESOLVED = [
  {
    id: "TD-26",
    description: "A deployed build had no API, so it showed the first screen and stopped: no medicines, no sign-in, no offers, no reservation. The v1 routes were served only by a vite middleware that is not in the production bundle. Worse, the first version of the routing made the failure DISHONEST — the catch-all rewrite answered GET /v1/catalogue/search with the HTML document and a 200, the app read that as an empty result, and the screen said «ما لكيناه بقائمتنا»: it told the patient the medicine is not in our catalogue. It is. The backend isn't.",
    resolvedBy: "Product decided the review build carries the mock rather than let a missing backend stop the workflow being reviewed, so `apps/patient/web/mock.ts` installs THE SAME `handle` the dev server runs — tools/devserver/api.mjs, one implementation of the contracts, not a second one that would drift. That file imports nothing from node; it speaks req/res, so the only thing missing in a browser was those two objects. It is imported only when VITE_MOCK_API is set, and lands in its own 3.6 kB chunk, so a build without the flag never carries it and a real backend replaces it by absence. Walked on the STATIC BUILD served the way Netlify serves it — search → draft → sign in → name → district → send → offers arriving → compare → substitution consent → reserved with a pickup code, no console errors. Separately: every deploy on this branch had been CANCELLED, and the cause was the root netlify.toml's base of `dawai-site` — Netlify skips a build when nothing in the base directory changed, and that folder had not been touched in months, so the preview URL kept showing an old static site while the app was never built at all. The base now points at `platform`. What remains is TD-1: this is a mock, and the data resets on reload.",
  },
  {
    id: "TD-9",
    description: "R2's shutter was SILENTLY inert — pressing «صوّر» left the screen, the controls and the state exactly as they were. No medicine that requires a prescription could be requested at all: D18 refuses the send without an image, the only way to attach one is a photograph, and none could be taken. The register called this a device problem for months, and that was wrong: a browser can take a photograph and `POST /v1/prescriptions` has been declared the entire time. The real obstacle was one line of this repository's own design — `Host.camera` returned an `imageId`, which a platform cannot know, because an id is minted by the media service. The interface was asking the host to do the app's job.",
    resolvedBy: "The host now returns bytes and nothing else: `camera(): Promise<{ localUri } | null>`, implemented in the browser with a hidden `<input type=\"file\" accept=\"image/*\" capture=\"environment\">` — the rear camera on a phone, a file picker on a laptop, where the paper has usually already been photographed — and a `cancel`/focus fallback so a dismissed picker resolves null instead of leaving «تصوير» pressed for ever. A new `MediaPort` (`infra/media.ts`) reads those bytes through an injectable `ReadImage` and uploads them over the declared route (multipart image + { subjectId } → 201 { imageId }, 413 too_large, 415 unsupported_type), with the content-type deliberately unset so the platform writes the multipart boundary. The two refusals are kept apart because they are different things to fix, a 201 with no id is a failure rather than a success the app cannot use, and an unreadable uri is permanent — R2 keeps the review state and the patient takes another. `Prescription.Capture` gained the moment that was missing between confirmed and attached: `uploading`, then `attached(imageId)` at the one place an id can enter, or `failed(localUri, reason)` which keeps the photograph retryable. Phase 0 still reads nothing (D18) — the dev server counts the bytes and discards them, logging «not stored (D18)». Walked in Chromium: a blocked prescription line, «صوّر», R3's review, «واضحة — كمّل», and R1 reading «الوصفة مرفقة».",
  },
  {
    id: "TD-18",
    description: "E7 (name) and E8 (district) could not be reached in the running app. `perform` mapped the declared 200 from POST /v1/auth/verify to the `authenticated` intent, which replayed the action the guard had interrupted (D26), while the path that navigates to E7 needed a `codeJudged` verdict of \"correct\" that nothing but a test produced. Both behaviours were declared — the Blueprint's screen graph draws E6 → E7 → E8 → S1, and D26 says the preserved action resumes — and the ORDER between them was not. Product answered: the name and the district first.",
    resolvedBy: "Verification authenticates the session and carries on to E7; the replay waits for the end of onboarding. E8's submit sends both answers in ONE call over the declared PATCH /v1/me (§4 M2 — { name?, districtId? } → 200, 400 invalid_district), because an account with a name and no district is one that cannot make a request. `profileSaved` then applies the district to the draft the GUEST built — `newDraft` had been given a guest's authority, so every request left with `districtId: \"\"` and a real server would have refused it — tells the composition root through a new `onDistrict` port, and only then replays what D26 preserved. A district the server refuses keeps the patient on E8 with E12's sentence, and a dropped connection says nothing at all rather than borrowing «ما اخترت منطقة» and blaming them for a network (TD-25). Proved by a test that fails when the district is not applied, and walked in Chromium: E6 → E7 → E8 → back to the request → sent, with the dev server logging «profile: أم علي in d1»."  },
  {
    id: "TD-5",
    description: "A substitution could be seen on R8 and accepted with the offer, while §4 R10 requires an explicit acknowledgement of a different brand. A flag on a row is not consent.",
    resolvedBy: "R9/R10 built. Consent is per line, starts undecided with no constructor that produces agreement, treats undecided as NOT agreed when computing what gets reserved, and blocks acceptance until every proposal is answered. Refusing sends the line to the child request (D06) and the screen says so, because a patient who believes refusing loses the order will agree to a brand they did not want.",
  },
  {
    id: "TD-4",
    description: "The sign-in chain E4 → E8 existed as screens and was wired to nothing: the app root rendered none of them, so a guest who touched an action needing an account was redirected by the guard and drawn the search screen instead. Signing in was then only half done — the store learned who had verified and the RUNTIME did not, so `authority()` still answered from an empty relationship set and the R6 guard refused a patient on the request they had verified in order to send.",
    resolvedBy: "The root renders E4–E8, and a new `onVerified` port tells the composition root who signed in at the moment the server says so. Authority is then answered from §9's invariant — an Account always owns exactly one self Subject, created atomically by POST /v1/auth/verify — supplied to `Authority.authorise`, which still decides: a memorialised subject is refused exactly as before (D04), and a grant over someone else is NOT inferred, because grants[] comes from GET /v1/me and no port reads it yet. Walked in Chromium: search → sign in → «أرسل الطلب» → R7 «انرسل — ننتظر الردود». What remains is separate and registered: E7 and E8 are still unreachable (TD-18), so the request carries no district.",
  },
  {
    id: "TD-19",
    description: "`isBuilt` meant \"this screen has a CONTRACT\", while its docstring promised what callers assumed: \"Nothing renders a control that leads to a screen that is not here.\" Four contracted screens have no component, so R1's «لمن؟» — the control for saying who the medicine is for — rendered, was tapped, navigated successfully, and landed on the root's `default`, which drew the SEARCH screen over the request the patient had just built. E4's «مو هسه — رجعني لطلبي» did the same by dismissing to S1, clearing the history on the way. The navigation gates could not see either: they prove the CONTRACT graph has no unreachable screen and no trap, and every one of these passes that.",
    resolvedBy: "`isBuilt` now means what it says — contracted AND drawable — so R4, R5, R11 and R13 are indistinguishable from a screen this build does not contract at all, and no control leads to one. S1 stays deliberately IN, with the reason stated at the list: it is the only missing screen the root substitutes for, every exit naming it means \"leave for Today\", and removing those would take «تمام — خبروني» off R7's offline state and leave a live request with no acknowledged way out. E4's dismiss is answered from D26 instead of from the graph — a dismiss with a preserved action returns to the screen the patient was using, and one without still lands where the graph says. Proved by two tests that press the controls through the real app root, and walked in Chromium. SINCE: S1 has been built, so it is no longer a substitution and the root no longer draws the search screen for it — and the guard this item created is now a gate rather than a convention, because `journey.test.tsx` fails the build when a screen `isBuilt` admits has no case in the app root.",
  },
  {
    id: "TD-0a",
    description: "layer-check scanned only .ts, so the app layer stopped being checked when it became .tsx.",
    resolvedBy: "Extended to .tsx and proven with a rejecting case.",
  },
  {
    id: "TD-0b",
    description: "Build output emitted beside sources, so tests ran against a stale build.",
    resolvedBy: "Project references corrected, stray output banned by layer-check, and .gitignore updated.",
  },
  {
    id: "TD-0c",
    description: "Prices were rounded to the nearest thousand, displaying 8,500 as '9 ألف'.",
    resolvedBy: "Exact formatting, with a test asserting two different totals never print identically.",
  },
];
