#!/usr/bin/env node
/**
 * A hash of every rendered screen, as TEXT.
 *
 * The visual regression that runs locally compares PNG bytes, and CI proved
 * those are not reproducible across environments: a runner drew all 44 screens
 * 5-10% smaller with identical content, because PNG output depends on the
 * Chromium build and the fonts present. That comparison is right on a
 * developer's machine against that same machine's previous output, and cannot
 * be run anywhere else.
 *
 * The HTML the renderer produces before any pixel exists has no such problem.
 * It is text, generated by React from source, with no rasterisation, no font
 * metrics and no timestamps in it — verified identical across repeated renders,
 * and containing nothing machine-specific.
 *
 * So this is what CI can honestly check: the component tree, the copy, the
 * inline styles and the accessibility attributes this commit renders are the
 * ones it recorded. It cannot see a font that failed to load or a shadow that
 * moved — the screenshots remain the only witness for those, locally.
 *
 * `--check` compares instead of writing, which is what the runner does.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const SCREENS = join(REPO, "review/screens");
const MANIFEST = join(REPO, "review/screens.sha256");

if (!existsSync(SCREENS)) {
  console.error("review/screens is empty — run npm run review:render first");
  process.exit(1);
}

const sha = (buf) => createHash("sha256").update(buf).digest("hex");
const current = readdirSync(SCREENS)
  .filter((f) => f.endsWith(".html")).sort()
  .map((f) => `${sha(readFileSync(join(SCREENS, f)))}  ${f}`)
  .join("\n") + "\n";

const checking = process.argv.includes("--check");

console.log(`\nRendered screens — recorded as text\n`);
console.log(`  ${current.trim().split("\n").length} screen(s)\n`);

if (!checking) {
  writeFileSync(MANIFEST, current);
  console.log(`  WROTE review/screens.sha256\n`);
  process.exit(0);
}

if (!existsSync(MANIFEST)) {
  console.log(`  FAIL  review/screens.sha256 is missing — run node tools/review/manifest.mjs\n`);
  process.exit(1);
}

const recorded = readFileSync(MANIFEST, "utf8");
if (recorded === current) {
  console.log(`  PASS  every screen renders exactly what this commit recorded\n`);
  process.exit(0);
}

const parse = (text) => new Map(text.trim().split("\n").map((l) => {
  const [h, ...rest] = l.split("  ");
  return [rest.join("  "), h];
}));
const was = parse(recorded);
const now = parse(current);
for (const [file, hash] of now) {
  if (!was.has(file)) console.log(`  FAIL  ${file} is new and unrecorded`);
  else if (was.get(file) !== hash) console.log(`  FAIL  ${file} renders differently than recorded`);
}
for (const file of was.keys()) if (!now.has(file)) console.log(`  FAIL  ${file} was recorded and no longer renders`);
console.log(`\nThe recorded render and this one disagree. Run npm run review and commit the result.\n`);
process.exit(1);
